### ISSUE TITLE
Jest mock sort not supported

### ISSUE THREAD

**Issue by mahoshojoHCG** [trivago/prettier-plugin-sort-imports#172]
**Your Environment**
 * **Prettier version**: 2.7.1
 * **node version** : 14.20.0
 * **package manager**: pnpm@5.14.3
 * **IDE**: VScode

**Describe the bug**

The plugin will sort jest mock after normal import

**To Reproduce**

For code:
``` ts

jest.mock("pkg", ...);

import { someThing } from "some-package";

```

It will be formated to 
``` ts
import { someThing } from "some-package";

jest.mock("pkg", ...);

```

Causing error when testing.

**Expected behavior**

Make jest.mock before the import.
``` ts

jest.mock("pkg", ...);

import { someThing } from "some-package";

```

**Contribute to @trivago/prettier-plugin-sort-imports**

- [ ] I'm willing to fix this bug 🥇

**Comment by savelevcorr** [comment]
@mahoshojoHCG 

I suppose there is no bug.
Because I have similar example in my project and everything works fine.

Just take a look, this is the code from my project:
```js
describe('OrganisationInfoContainer', () => {
  jest.mock(
    '../../management-component/management-component',
    () => () => {
      return <div data-testid="fake-test-id"} />;
    }
  );

// ... rest of my test cases
};
```
Also, there is a best-practice rule to keep all your named imports at the top of the file.

Maybe you have some dependencies between what you wanna mock and what you wanna import?
In this case the order is matter. If it is true, so you need to fix this dependency.
