### ISSUE TITLE
Fails to format when await used in try block

### ISSUE THREAD

**Issue by DanielPower** [trivago/prettier-plugin-sort-imports#28]
prettier 2.2.1
sort-imports 1.4.1
node 14.15.4
Archlinux

Input:
```javascript
try {
    result = await test();
} catch (e) {
  result = false;
}
```

Without this plugin, the above example formats correctly. With this plugin, we get the following error:

```
[error] prettiertest.js: SyntaxError: Unexpected token, expected ";" (3:19)
[error]   1 | const result;
[error]   2 | try {
[error]   3 |     result = await test();
[error]   4 | } catch (e) {
[error]   5 |   result = false;
[error]   6 | }
[error]   7 | 
```

**Comment by ayusharma** [comment]
The plugin uses babel to parse the provided `js/ts` files. If your code is invalid then plugin will throw an error. 

At line 1:  'const' declarations must be initialized 
At line 3: cannot assign to 'result' because it is a constant.

You can use `let result;` and then give a try. 

Please feel free to reopen if the issue persists.
